---
name: 🤖 Docker Tests

on: workflow_call

env:
  DOCKER_BUILDKIT: 1

# TODO: Add independent job that builds the images.
jobs:
  docker-torch-unit:
    name: ☁️ Pytorch Image Tests [Container]
    runs-on: ubuntu-latest
    steps:
      - name: 🐄 checkout armory full depth with tags for scm
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get history and tags for SCM versioning to work
      # yamllint disable rule:indentation
      - name: 📩 Checkout the Source
        run: |
          git fetch --prune --unshallow || true
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          # Verify .git folder
          if [ ! -d "./.git" ]; then
            echo "Expected ./.git folder to exist"
            exit 1
          fi
      # yamllint enable rule:indentation

      - name: 🐍 Use Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: ⚙️ Installing Armory
        shell: bash
        run: |
          python -m pip install --upgrade pip build
          pip install .
          armory configure --use-defaults

      - name: 🚧 Build the Container
        run: |
          python docker/build.py --framework pytorch

      # TODO: Create/mount a volume with the tests and config files.
      # yamllint disable rule:indentation
      - name: 🤞 Run Image tests
        run: |
          IMAGE_VERSION=`armory --show-docker-version-tag`
          docker run                                  \
            --rm                                      \
            --workdir /armory-repo                    \
            twosixarmory/pytorch:${IMAGE_VERSION}    \
              pytest                                  \
                -c /armory-repo/pyproject.toml        \
                -m "not docker_required and unit"     \
                ./tests/

  docker-tf2-unit:
    name: ☁️ Docker TF2 Image Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🐄 checkout armory full depth with tags for scm
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Use Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: ⚙️ Installing Armory
        shell: bash
        run: |
          python -m pip install --upgrade pip build
          pip install .
          armory configure --use-defaults

      - name: 🚧 Build the Container
        run: |
          python docker/build.py --framework tf2

      # yamllint disable rule:indentation
      - name: 🤞 Run Image tests
        run: |
          IMAGE_VERSION=`python -m armory.utils.get_docker_version`
          docker run                                  \
            --rm                                      \
            --workdir /armory-repo                    \
            twosixarmory/tf2:${IMAGE_VERSION}        \
              pytest                                  \
                -c /armory-repo/pyproject.toml        \
                -m "not docker_required and unit"     \
                ./tests/
      # yamllint enable rule:indentation


  docker-deepspeech-unit:
    name: ☁️ Docker Deepspeech Image Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🐄 checkout armory full depth with tags for scm
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🐍 Use Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: ⚙️ Installing Armory
        shell: bash
        run: |
          python -m pip install --upgrade pip build
          pip install --no-compile --editable .
          armory configure --use-defaults

      - name: 🚧 Build the Container
        run: |
          python docker/build.py --framework pytorch-deepspeech

      # yamllint disable rule:indentation
      - name: 🤞 Run Image tests
        run: |
          IMAGE_VERSION=`python -m armory.utils.get_docker_version`

          docker run                                           \
            --rm                                               \
            --workdir /armory-repo                             \
            twosixarmory/pytorch-deepspeech:${IMAGE_VERSION}  \
              pytest                                           \
                -c /armory-repo/pyproject.toml                 \
                -m "not docker_required and unit"              \
                ./tests/

            docker run                                         \
            --rm                                               \
            --workdir /armory-repo                             \
            twosixarmory/pytorch-deepspeech:${ARMORY_VERSION}  \
              pytest                                           \
                -c /armory-repo/pyproject.toml                 \
                -m "pytorch_deepspeech"                        \
                ./tests/
      # yamllint enable rule:indentation
